# Generated by Django 2.2 on 2019-04-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='post_image')),
            ],
        ),
        migrations.CreateModel(
            name='canvas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='post_image')),
            ],
        ),
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='post_image')),
                ('nota', models.CharField(max_length=20)),
                ('title2', models.CharField(max_length=20)),
                ('image2', models.ImageField(upload_to='post_image')),
            ],
        ),
        migrations.CreateModel(
            name='mision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='planilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image1', models.ImageField(upload_to='post_image')),
                ('image2', models.ImageField(upload_to='post_image')),
                ('image3', models.ImageField(upload_to='post_image')),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('info', models.ImageField(upload_to='post_image')),
                ('image', models.ImageField(upload_to='post_image')),
            ],
        ),
        migrations.CreateModel(
            name='verfication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=20)),
                ('image1', models.ImageField(upload_to='post_image')),
                ('image11', models.ImageField(upload_to='post_image')),
                ('title2', models.CharField(max_length=20)),
                ('image2', models.ImageField(upload_to='post_image')),
                ('image22', models.ImageField(upload_to='post_image')),
                ('title3', models.CharField(max_length=20)),
                ('image3', models.ImageField(upload_to='post_image')),
                ('image33', models.ImageField(upload_to='post_image')),
                ('title4', models.CharField(max_length=20)),
                ('image4', models.ImageField(upload_to='post_image')),
                ('image44', models.ImageField(upload_to='post_image')),
                ('objetivos', models.ImageField(upload_to='post_image')),
            ],
        ),
        migrations.CreateModel(
            name='vision2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('body', models.TextField()),
            ],
        ),
    ]
